CREATE TABLE Farmer (
  farmer_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(100) NOT NULL,
  contact      VARCHAR2(100)
);

CREATE TABLE Cooperative (
  coop_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(100) NOT NULL,
  location     VARCHAR2(100)
);
CREATE TABLE Asset (
  asset_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  farmer_id    NUMBER NOT NULL,
  type         VARCHAR2(20)  NOT NULL CHECK (type IN ('CROP','LIVESTOCK')),
  subtype      VARCHAR2(50)  NOT NULL,
  CONSTRAINT fk_asset_farmer FOREIGN KEY(farmer_id)
    REFERENCES Farmer(farmer_id)
);

CREATE TABLE Season (
  season_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  asset_id       NUMBER NOT NULL,
  start_date     DATE         NOT NULL,
  expected_yield NUMBER(10,2) DEFAULT 0,
  CONSTRAINT fk_season_asset FOREIGN KEY(asset_id)
    REFERENCES Asset(asset_id)
);

CREATE TABLE Activity (
  activity_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  season_id      NUMBER NOT NULL,
  activity_type  VARCHAR2(50) NOT NULL CHECK (activity_type IN (
                      'Planting','Fertilization','Pest Control',
                      'Vaccination','Disease Control','Feeding','Health Check')),
  amount         NUMBER(10,2) NOT NULL,
  activity_date  DATE         NOT NULL,
  CONSTRAINT fk_activity_season FOREIGN KEY(season_id)
    REFERENCES Season(season_id)
);
CREATE TABLE Harvest (
  harvest_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  season_id      NUMBER NOT NULL UNIQUE,
  actual_yield   NUMBER(10,2) NOT NULL,
  harvest_date   DATE         NOT NULL,
  CONSTRAINT fk_harvest_season FOREIGN KEY(season_id)
    REFERENCES Season(season_id)
);
CREATE TABLE Report (
  report_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  season_id      NUMBER NOT NULL,
  coop_id        NUMBER NOT NULL,
  report_text  CLOB         NOT NULL,
  report_date  DATE         NOT NULL,
  CONSTRAINT fk_report_season FOREIGN KEY(season_id)
    REFERENCES Season(season_id),
  CONSTRAINT fk_report_coop   FOREIGN KEY(coop_id)
    REFERENCES Cooperative(coop_id)
);


commit;
